"""Обновление моделей

Revision ID: 7370b9a98c6c
Revises: 877d24da2c8c
Create Date: 2024-10-08 14:00:21.303740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7370b9a98c6c'
down_revision = '877d24da2c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('response')
        batch_op.drop_column('search_query')

    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_password', sa.String(length=200), nullable=False))
        batch_op.drop_column('system_password_encrypted')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('system_password_encrypted', sa.BLOB(), nullable=False))
        batch_op.drop_column('system_password')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('response', sa.TEXT(), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('role')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
